### ISSUE TITLE
Typed.js not writing into newly generated elements

### ISSUE THREAD

**Issue by Hmastery** [mattboldt/typed.js#302]
### Description

I am trying to use typed.js to write into a div generated using jquery append().
But it seems that typed won't listen to them.

How can I solve this issue ? I know I should use jquery on() but I don't know how in this very specific case.

### Demo

`i = 0;
    function next_question()
    {

        $(".conversation").append("<div id='"+i+"question' class='convo_bubble_aldrugo'></div>");

        new Typed('#'+i+'question', {
        strings: ['question content'],
        typeSpeed: 6,
            bindInputFocusEvents: true,
        contentType: 'html'
        });  
        i++;
    }`

Error received:

> Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#0question' is not a valid selector.
    at t.value (http://localhost/test/js/typed.custom.js:10:6878)
    at new t (http://localhost/test/js/typed.custom.js:10:903)
    at next_question (http://localhost/test/js/actions.js:789:9)
    at HTMLDocument.<anonymous> (http://localhost/test/js/actions.js:797:1)
    at j (http://localhost/test/js/plugins/jquery/jquery.min.js:2:26860)
    at Object.fireWith [as resolveWith] (http://localhost/test/js/plugins/jquery/jquery.min.js:2:27673)
    at Function.ready (http://localhost/test/js/plugins/jquery/jquery.min.js:2:29467)
    at HTMLDocument.I (http://localhost/test/js/plugins/jquery/jquery.min.js:2:29658)

**Comment by mattboldt** [comment]
An HTML ID selector can't start with a number
